<?php
/**
 * Created by PhpStorm.
 * User: Zluis
 * Date: 05/12/2016
 * Time: 02:40
 */

namespace app\Classes;

$magicSets =array(
    array("Kaladesh"=>"http://magiccards.info/kld/en.html","load"=>'1'),
    array("Eldritch Moon"=>"http://magiccards.info/emn/en.html","load"=>'1'),
    array("Shadows over Innistrad"=>"http://magiccards.info/soi/en.html","load"=>'1'),
    array("Oath of the Gatewatch"=>"http://magiccards.info/ogw/en.html","load"=>'1'),
    array("Battle for Zendikar"=>"http://magiccards.info/bfz/en.html","load"=>'1'),
    array("Dragons of Tarkir"=>"http://magiccards.info/dtk/en.html","load"=>'1'),
    array("Fate Reforged"=>"http://magiccards.info/frf/en.html","load"=>'1'),
    array("Khans of Tarkir"=>"http://magiccards.info/ktk/en.html","load"=>'1'),
    array("Journey into Nyx"=>"http://magiccards.info/jou/en.html","load"=>'1'),
    array("Born of the Gods"=>"http://magiccards.info/bng/en.html","load"=>'1'),
    array("Theros"=>"http://magiccards.info/ths/en.html","load"=>'1'),
    array("Dragon's Maze"=>"http://magiccards.info/dgm/en.html","load"=>'1'),
    array("Gatecrash"=>"http://magiccards.info/gtc/en.html","load"=>'1'),
    array("Return to Ravnica"=>"http://magiccards.info/rtr/en.html","load"=>'1'),
    array("Avacyn Restored"=>"http://magiccards.info/avr/en.html","load"=>'1'),
    array("Dark Ascension"=>"http://magiccards.info/dka/en.html","load"=>'1'),
    array("Innistrad"=>"http://magiccards.info/isd/en.html","load"=>'1'),
    array("New Phyrexia"=>"http://magiccards.info/nph/en.html","load"=>'1'),
    array("Mirrodin Besieged"=>"http://magiccards.info/mbs/en.html","load"=>'1'),
    array("Scars of Mirrodin"=>"http://magiccards.info/som/en.html","load"=>'1'),
    array("Rise of the Eldrazi"=>"http://magiccards.info/roe/en.html","load"=>'1'),
    array("Worldwake"=>"http://magiccards.info/wwk/en.html","load"=>'1'),
    array("Zendikar"=>"http://magiccards.info/zen/en.html","load"=>'1'),
    array("Alara Reborn"=>"http://magiccards.info/arb/en.html","load"=>'1'),
    array("Conflux"=>"http://magiccards.info/cfx/en.html","load"=>'1'),
    array("Shards of Alara"=>"http://magiccards.info/ala/en.html","load"=>'1'),
    array("Eventide"=>"http://magiccards.info/eve/en.html","load"=>'1'),
    array("Shadowmoor"=>"http://magiccards.info/shm/en.html","load"=>'1'),
    array("Morningtide"=>"http://magiccards.info/mt/en.html","load"=>'1'),
    array("Lorwyn"=>"http://magiccards.info/lw/en.html","load"=>'1'),
    array("Future Sight"=>"http://magiccards.info/fut/en.html","load"=>'1'),
    array("Planar Chaos"=>"http://magiccards.info/pc/en.html","load"=>'1'),
    array("Time Spiral"=>"http://magiccards.info/ts/en.html","load"=>'1'),
    array("Time Spiral Timeshifted"=>"http://magiccards.info/tsts/en.html","load"=>'1'),
    array("Coldsnap"=>"http://magiccards.info/cs/en.html","load"=>'1'),
    array("Alliances"=>"http://magiccards.info/ai/en.html","load"=>'1'),
    array("Ice Age"=>"http://magiccards.info/ia/en.html","load"=>'1'),
    array("Dissension"=>"http://magiccards.info/di/en.html","load"=>'1'),
    array("Guildpact"=>"http://magiccards.info/gp/en.html","load"=>'1'),
    array("Ravnica: City of Guilds"=>"http://magiccards.info/rav/en.html","load"=>'1'),
    array("Saviors of Kamigawa"=>"http://magiccards.info/sok/en.html","load"=>'1'),
    array("Betrayers of Kamigawa"=>"http://magiccards.info/bok/en.html","load"=>'1'),
    array("Champions of Kamigawa"=>"http://magiccards.info/chk/en.html","load"=>'1'),
    array("Fifth Dawn"=>"http://magiccards.info/5dn/en.html","load"=>'1'),
    array("Darksteel"=>"http://magiccards.info/ds/en.html","load"=>'1'),
    array("Mirrodin"=>"http://magiccards.info/mi/en.html","load"=>'1'),
    array("Scourge"=>"http://magiccards.info/sc/en.html","load"=>'1'),
    array("Legions"=>"http://magiccards.info/le/en.html","load"=>'1'),
    array("Onslaught"=>"http://magiccards.info/on/en.html","load"=>'1'),
    array("Judgment"=>"http://magiccards.info/ju/en.html","load"=>'1'),
    array("Torment"=>"http://magiccards.info/tr/en.html","load"=>'1'),
    array("Odyssey"=>"http://magiccards.info/od/en.html","load"=>'1'),
    array("Apocalypse"=>"http://magiccards.info/ap/en.html","load"=>'1'),
    array("Planeshift"=>"http://magiccards.info/ps/en.html","load"=>'1'),
    array("Invasion"=>"http://magiccards.info/in/en.html","load"=>'1'),
    array("Prophecy"=>"http://magiccards.info/pr/en.html","load"=>'1'),
    array("Nemesis"=>"http://magiccards.info/ne/en.html","load"=>'1'),
    array("Mercadian Masques"=>"http://magiccards.info/mm/en.html","load"=>'1'),
    array("Urza's Destiny"=>"http://magiccards.info/ud/en.html","load"=>'1'),
    array("Urza's Legacy"=>"http://magiccards.info/ul/en.html","load"=>'1'),
    array("Urza's Saga"=>"http://magiccards.info/us/en.html","load"=>'1'),
    array("Exodus"=>"http://magiccards.info/ex/en.html","load"=>'1'),
    array("Stronghold"=>"http://magiccards.info/sh/en.html","load"=>'1'),
    array("Tempest"=>"http://magiccards.info/tp/en.html","load"=>'1'),
    array("Weatherlight"=>"http://magiccards.info/wl/en.html","load"=>'1'),
    array("Visions"=>"http://magiccards.info/vi/en.html","load"=>'1'),
    array("Mirage"=>"http://magiccards.info/mr/en.html","load"=>'1'),
    array("Homelands"=>"http://magiccards.info/hl/en.html","load"=>'1'),
    array("Fallen Empires"=>"http://magiccards.info/fe/en.html","load"=>'1'),
    array("The Dark"=>"http://magiccards.info/dk/en.html","load"=>'1'),
    array("Legends"=>"http://magiccards.info/lg/en.html","load"=>'1'),
    array("Antiquities"=>"http://magiccards.info/aq/en.html","load"=>'1'),
    array("Arabian Night"=>"http://magiccards.info/an/en.html","load"=>'1'));